### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dannyjunlee** [dannyjunlee/project1-group4#4]
- [ ] ? - create function to put all s&p names into autocomplete form
- [ ] ? - create function to show one stock in top box (by name search or first in sector search)
- [ ] ? - create function to show 3 sector stocks in bottom box (2nd-4th in sector search or 1st 3 in same sector as name search)
- [ ] Joshua - revise presentation template to fit our product
